[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1710:Identifiers should have correct suffix")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0063:Use simple 'using' statement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0066:Convert switch statement to expression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles")]
